import { StyleSheet } from "react-native";

// init
export const HEIGHT_STAT_GAUGE_CONTAINER = 34;
export const BORDER_RADIUS_STAT_GAUGE_CONTAINER = HEIGHT_STAT_GAUGE_CONTAINER / 2; // 17

// Spacing
export const PADDING_SEARCH_CONTAINER = 7;
export const LIST_ITEM_SPACING = 4;
export const PADDING_HORIZONTAL_ELEMENT_CARD = 20; // For screen-level padding
export const PADDING_PANNEL_PAGINATED = 6;
export const MARGIN_HORIZONTAL_MODAL_CHILDREN_CONTAINER = 10;
export const MARGIN_CONTAINER_LOWEST = 16;
export const GAP_SORT_MODE_SELECTOR = 7;
export const PADDING_STANDARD = 10;
export const PADDING_BOX_CONTAINER = PADDING_STANDARD;
export const PADDING_BUILD_CARD = 10;
export const GAP_ELEMENTS_GRID = 5;
export const GAP_STAT_GAUGE_GROUP = 5;
export const PADDING_VERTICAL_BUILD_IMAGES_CONTAINER = 7;
export const GAP_BUILD_IMAGES_CONTAINER = 14;

// calc
export const BORDER_RADIUS_CONTAINER_LOWEST = BORDER_RADIUS_STAT_GAUGE_CONTAINER + PADDING_SEARCH_CONTAINER; // 24
export const BORDER_RADIUS_STANDARD = BORDER_RADIUS_CONTAINER_LOWEST - PADDING_STANDARD; // 14

/**** Border Radius ****/

// Material 3 constants
export const CORNER_SMALL = 8;
export const BORDER_RADIUS_MEDIUM = 10;
export const CORNER_LARGE = 16;
export const CORNER_LARGE_INCREASED = 20;
export const CORNER_EXTRA_LARGE = 28;
export const CORNER_EXTRA_LARGE_INCREASED = 32;
export const CORNER_EXTRA_EXTRA_LARGE = 48;

export const BORDER_RADIUS_18 = 18; // More prominent rounded corners
export const BORDER_RADIUS_INF = 200;
export const BORDER_RADIUS_CATEGORY_SELECTOR = 24; // au lieu de BORDER_RADIUS_STANDARD - PADDING_PAGINATED_WRAPPER_CONTAINER; // = 6

export const BORDER_RADIUS_INPUT = 7;

export const BORDER_RADIUS_MODAL_CHILDREN_CONTAINER = BORDER_RADIUS_STANDARD;
export const BORDER_RADIUS_MODAL_CONTAINER =
  BORDER_RADIUS_MODAL_CHILDREN_CONTAINER + MARGIN_HORIZONTAL_MODAL_CHILDREN_CONTAINER;

export const ELEMENT_LONG_IMAGE_SIZE = 60;
export const ELEMENT_LONG_IMAGE_RATIO = 1.1;

// Largeurs définies pour la colonne de gauche
export const LEFT_PANNEL_WIDTH_EXPANDED = ELEMENT_LONG_IMAGE_SIZE * 4 + LIST_ITEM_SPACING * 2;
export const LEFT_PANNEL_WIDTH_COLLAPSED = ELEMENT_LONG_IMAGE_SIZE + LIST_ITEM_SPACING * 2;

export const WIDTH_BUILD_CARD = 220;
export const WIDTH_BUILD_CARD_CONTENT = WIDTH_BUILD_CARD - 2 * PADDING_BUILD_CARD; // * 200

export const MAX_WIDTH_IN_BUILD_CARD = WIDTH_BUILD_CARD - PADDING_BUILD_CARD * 2; // 200

export const BUTTON_SIZE = 40;
export const HEIGHT_BUTTON_RECTANGLE = 30;
export const WIDTH_BUTTON_RECTANGLE = 46;

export const buttonPressed = {
  opacity: 0.8, // léger effet d’opacité
};
